# Generated by Django 4.1.6 on 2023-02-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='Email_text',
            field=models.TextField(null=True),
        ),
    ]
