# Generated by Django 4.1.6 on 2023-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_changes_email_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='Email_text',
            new_name='email_text',
        ),
        migrations.RemoveField(
            model_name='changes',
            name='Zeit',
        ),
        migrations.AddField(
            model_name='changes',
            name='email_zeit',
            field=models.IntegerField(null=True),
        ),
    ]
