# Generated by Django 4.1.6 on 2023-02-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_email_text_changes_email_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='email_betreff',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
