# Generated by Django 4.1.6 on 2023-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_changes_email_betreff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='email_zeit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
