# Generated by Django 4.2.6 on 2023-10-14 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KundenDaten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nachname", models.CharField(max_length=200)),
                ("vorname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefon", models.CharField(max_length=200)),
                ("strasse", models.CharField(max_length=200)),
                ("ort_plz", models.CharField(max_length=200)),
                ("krankenkasse", models.CharField(max_length=200)),
                ("kv_nummer", models.CharField(max_length=200)),
                ("geburtsdatum", models.DateField(default=django.utils.timezone.now)),
                (
                    "geschlecht",
                    models.CharField(
                        choices=[
                            ("Mann", "Mann"),
                            ("Frau", "Frau"),
                            ("nicht definiert", "nicht definiert"),
                        ],
                        default="nicht definiert",
                        max_length=20,
                    ),
                ),
                ("notiz", models.CharField(blank=True, max_length=1000, null=True)),
                ("emailDaten", models.JSONField(default=dict)),
                ("erstellt", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
