# Generated by Django 4.1.6 on 2023-02-07 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=200)),
                ('vorname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=200)),
                ('strasse', models.CharField(max_length=200)),
                ('ort_plz', models.CharField(max_length=200)),
                ('krankenkasse', models.CharField(max_length=200)),
                ('geburtsdatum', models.DateField()),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
