# Generated by Django 4.1.6 on 2023-02-19 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='geschlecht',
            field=models.CharField(choices=[('Mann', 'Mann'), ('Frau', 'Frau'), ('nicht definiert', 'nicht definiert')], default='nicht definiert', max_length=20),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='notiz',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='geburtsdatum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
