# Generated by Django 4.2.6 on 2023-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kundendaten",
            name="unterschrift",
            field=models.ImageField(blank=True, null=True, upload_to="unterschriften/"),
        ),
    ]
