# Generated by Django 4.2.6 on 2023-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_kundendaten_unterschrift"),
    ]

    operations = [
        migrations.RemoveField(model_name="kundendaten", name="unterschrift",),
        migrations.AddField(
            model_name="kundendaten",
            name="verbindungsCode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
