# Generated by Django 4.1.6 on 2023-02-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_userinformation_email_after_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='email_after_3',
            field=models.BooleanField(default=False),
        ),
    ]
