# Generated by Django 4.1.6 on 2023-02-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_userinformation_email_after_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='email_after_2',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email_after_3',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='email_after_4',
            field=models.BooleanField(default=False),
        ),
    ]
