# Generated by Django 4.1.6 on 2023-02-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_remove_userinformation_email_after_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='email_after_5',
            field=models.BooleanField(default=False),
        ),
    ]
