# Generated by Django 4.1.6 on 2023-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_userinformation_email_after_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='email_after_4',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email_after_5',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='gesendet',
            field=models.JSONField(default={'apfel': 'grün', 'haus': 'rot'}),
        ),
    ]
