# Generated by Django 4.1.6 on 2023-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_userinformation_email_after_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='gesendet',
            field=models.JSONField(default={'apfel': 'pink', 'haus': 'rot'}),
        ),
    ]
