# Generated by Django 4.2.4 on 2023-08-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_userinformation_gesendet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='gesendet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
