# Generated by Django 4.2.4 on 2023-08-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_userinformation_gesendet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='gesendet',
            new_name='emailDaten',
        ),
    ]
