# Generated by Django 4.2.6 on 2023-11-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfVerarbeitung", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unterschriftsverknuepfung",
            name="unterschriftPfad",
            field=models.ImageField(blank=True, null=True, upload_to="unterschriften/"),
        ),
        migrations.AlterField(
            model_name="unterschriftsverknuepfung",
            name="verbindungsCode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
