# Generated by Django 4.2.6 on 2023-11-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pdfVerarbeitung",
            "0002_alter_unterschriftsverknuepfung_unterschriftpfad_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GeradeAngemeldet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verbindungsCode", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
