# Generated by Django 4.2.6 on 2023-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfVerarbeitung", "0003_geradeangemeldet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leistungserbringer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(blank=True, max_length=200, null=True)),
                ("nachname", models.CharField(blank=True, max_length=200, null=True)),
                ("ort", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
