# Generated by Django 4.2.6 on 2024-01-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdfVerarbeitung", "0004_leistungserbringer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leistungserbringer", old_name="ort", new_name="adresse",
        ),
    ]
